export const productCard: string;
export const productImg: string;
export const productDescription: string;
export const buttonsContainer: string;
export const buttonMinus: string;
export const buttonMinus: string;
export const countLabel: string;
export const buttonAdd: string;
export const disabled: string;
